"""add analysis columns

Revision ID: b8dd4df63389
Revises: 8b3db66e58bf
Create Date: 2026-07-22 14:58:17.431474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dd4df63389'
down_revision: Union[str, Sequence[str], None] = '8b3db66e58bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('analysis', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('analysis_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis_status')
    op.drop_column('resumes', 'analysis')
    # ### end Alembic commands ###
